### ISSUE TITLE
[BUG] crash shortly after launch (core dumped)

### ISSUE THREAD

**Issue by rexbinary** [aristocratos/btop#331]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

btop crashes shortly after launch with the error as seen in the screenshot below. No actions are taken or needed for the crash to occur.

**To Reproduce**

1. Launch btop.
2. Wait a bit. No longer than a minute or two.

**Expected behavior**

1. Launch btop
2. btop continues to run without crashing.

**Screenshots**

![Screenshot_20220508_231626](https://user-images.githubusercontent.com/740274/167339748-34a869e8-bdea-4839-b0ae-165567db4fab.png)

**Info (please complete the following information):**
 - btop++ version: 1.2.6
 - Binary: static binary from release
 - (If compiled) Compiler and version: n/a
 - Architecture: [x86_64, aarch64, etc.] x86_64
 - Platform: [Linux, FreeBSD, OsX] Linux
 - (Linux) Kernel: 5.17.4-1-default
 - (OSX/FreeBSD) Os release version: NAME="openSUSE Tumbleweed" # VERSION="20220506"
 - Terminal used: alacritty
 - Font used: MesloLGS NF

**Additional context**

contents of `~/.config/btop/btop.log`

[btop.log](https://github.com/aristocratos/btop/files/8648761/btop.log)

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run (linux): `gdb btop` (macos): `lldb btop`

3. `r` to run, wait for crash and press enter if prompted, CTRL+L to clear screen if needed.

4. (gdb): `thread apply all bt` (lldb): `bt all` to get backtrace for all threads

5. Copy and paste the backtrace here:

```
Thread 4 (Thread 0x7ffff6703640 (LWP 27806) "btop"):
#0  __GI___libc_read (nbytes=8191, buf=0x7fffe800a6d0, fd=5) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=5, buf=0x7fffe800a6d0, nbytes=8191) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007ffff7e501ff in std::__basic_file<char>::xsgetn (this=this@entry=0x7ffff67015b8, __s=0x7fffe800a6d0 "4066 (plasmashell) S 3965 1620 1620 0 -1 4194304 249911 2042330 1941 87168 960 737 7257 3236 20 0 81 0 1591 6985117696 126957 18446744073709551615 94194992877568 94194993194677 140723725921056 0 0 0 0"..., __n=__n@entry=8191) at basic_file.cc:337
#3  0x00007ffff7e8ffc8 in std::basic_filebuf<char, std::char_traits<char> >::underflow (this=0x7ffff6701550) at /usr/src/debug/gcc12-12.0.1+git192423-1.2.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/streambuf:487
#4  0x00007ffff7e4702c in std::basic_streambuf<char, std::char_traits<char> >::sgetc (this=0x7ffff6701550) at /usr/src/debug/gcc12-12.0.1+git192423-1.2.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/streambuf:343
#5  std::basic_streambuf<char, std::char_traits<char> >::sgetc (this=0x7ffff6701550) at /usr/src/debug/gcc12-12.0.1+git192423-1.2.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/streambuf:343
#6  std::istream::ignore (this=0x7ffff6701540, __n=9223372036854775807, __delim=32) at ../../../../../libstdc++-v3/src/c++98/istream.cc:128
#7  0x000055555560a02e in Proc::collect(bool) ()
#8  0x000055555558e33e in Runner::_runner(void*) ()
#9  0x00007ffff7ae42ba in start_thread (arg=<optimized out>) at pthread_create.c:442
#10 0x00007ffff7b6e460 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7ffff6f6c640 (LWP 27785) "btop"):
#0  __GI___libc_read (nbytes=8191, buf=0x5555556dbe80, fd=0) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=0, buf=0x5555556dbe80, nbytes=8191) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007ffff7e501ff in std::__basic_file<char>::xsgetn (this=this@entry=0x7ffff7fa1b08 <__gnu_internal::buf_cin+104>, __s=0x5555556dbe80 "", __n=__n@entry=8191) at basic_file.cc:337
#3  0x00007ffff7e8ffc8 in std::basic_filebuf<char, std::char_traits<char> >::underflow (this=0x7ffff7fa1aa0 <__gnu_internal::buf_cin>) at /usr/src/debug/gcc12-12.0.1+git192423-1.2.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/streambuf:487
#4  0x00007ffff7ec5726 in std::basic_streambuf<char, std::char_traits<char> >::uflow (this=0x7ffff7fa1aa0 <__gnu_internal::buf_cin>) at /usr/src/debug/gcc12-12.0.1+git192423-1.2.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/streambuf:708
#5  0x00007ffff7e9d26e in std::basic_streambuf<char, std::char_traits<char> >::sbumpc (this=<optimized out>) at /usr/src/debug/gcc12-12.0.1+git192423-1.2.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/streambuf:321
#6  std::basic_streambuf<char, std::char_traits<char> >::sbumpc (this=<optimized out>) at /usr/src/debug/gcc12-12.0.1+git192423-1.2.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/streambuf:321
#7  std::istream::get (this=0x555555678640 <std::cin>, __c=@0x7ffff6f6bdff: 0 '\000') at /usr/src/debug/gcc12-12.0.1+git192423-1.2.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/bits/istream.tcc:291
#8  0x00005555555cc954 in Input::InputThr::run(Input::InputThr*) ()
#9  0x00007ffff7e5a963 in std::execute_native_thread_routine (__p=0x555555726490) at ../../../../../libstdc++-v3/src/c++11/thread.cc:82
#10 0x00007ffff7ae42ba in start_thread (arg=<optimized out>) at pthread_create.c:442
#11 0x00007ffff7b6e460 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7ffff776d640 (LWP 27784) "btop" (Exiting)):
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff7ae61e3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7a96306 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7a7f813 in __GI_abort () at abort.c:79
#4  0x00007ffff7e23ad5 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007ffff7e2efcc in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007ffff7e2f037 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007ffff7e2e8ec in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, actions=10, exception_class=0, ue_header=<optimized out>, context=0x7ffff7769250) at ../../../../libstdc++-v3/libsupc++/eh_personality.cc:673
#8  0x00007ffff7c88de6 in _Unwind_ForcedUnwind_Phase2 (exc=0x7ffff776dcb0, context=0x7ffff7769250, frames_p=0x7ffff7769158) at ../../../libgcc/unwind.inc:183
#9  0x00007ffff7c894e0 in _Unwind_ForcedUnwind (exc=0x7ffff776dcb0, stop=stop@entry=0x7ffff7aecf7e <unwind_stop>, stop_argument=<optimized out>) at ../../../libgcc/unwind.inc:218
#10 0x00007ffff7aed126 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:130
#11 0x00007ffff7ae2677 in __do_cancel () at ../sysdeps/nptl/pthreadP.h:281
#12 sigcancel_handler (sig=32, si=0x7ffff77694f0, ctx=<optimized out>) at pthread_cancel.c:56
#13 sigcancel_handler (sig=<optimized out>, si=0x7ffff77694f0, ctx=<optimized out>) at pthread_cancel.c:32
#14 <signal handler called>
#15 0x00007ffff7b6f776 in __libc_sendto (fd=3, buf=buf@entry=0x7ffff776b060, len=len@entry=20, flags=flags@entry=0, addr=..., addr@entry=..., addrlen=addrlen@entry=12) at ../sysdeps/unix/sysv/linux/sendto.c:27
#16 0x00007ffff7b88d6b in __netlink_sendreq (type=18, h=0x7ffff776b120) at ../sysdeps/unix/sysv/linux/ifaddrs.c:119
#17 __netlink_request (h=h@entry=0x7ffff776b120, type=type@entry=18) at ../sysdeps/unix/sysv/linux/ifaddrs.c:157
#18 0x00007ffff7b8911e in getifaddrs_internal (ifap=0x7ffff776b230) at ../sysdeps/unix/sysv/linux/ifaddrs.c:335
#19 0x00007ffff7b89de8 in __GI___getifaddrs (ifap=0x7ffff776b230) at ../sysdeps/unix/sysv/linux/ifaddrs.c:837
#20 0x00005555555febec in Net::collect(bool) ()
#21 0x000055555558e1cb in Runner::_runner(void*) ()
#22 0x00007ffff7ae42ba in start_thread (arg=<optimized out>) at pthread_create.c:442
#23 0x00007ffff7b6e460 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7ffff7a3d740 (LWP 27780) "btop"):
#0  0x00007ffff7b31955 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffffffd2d0, rem=0x7fffffffd2d0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x00007ffff7b369c7 in __GI___nanosleep (req=<optimized out>, rem=<optimized out>) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x000055555563d4bb in Tools::atomic_wait_for(std::atomic<bool> const&, bool, unsigned long) [clone .constprop.0] ()
#3  0x00005555555994ec in Runner::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool) ()
#4  0x00005555555709fc in main ()
```

**Comment by rexbinary** [comment]
Since receiving an update to kernel 5.17.5 I am unable to reproduce this issue.
