### ISSUE TITLE
[BUG] btop randomly crashing when fstrim is being performed

### ISSUE THREAD

**Issue by TheComputerGuy96** [aristocratos/btop#492]
**Describe the bug**

For some reason, I discovered that `btop` randomly crashes with a few errors when `fstrim` is being performed (it doesn't happen otherwise)

It took forever to reproduce this because `fstrim` only runs weekly and I had no debug symbols for most of that time

Restarting `btop` makes it work again though :frog:

Once I had debug symbols, I saw in one of the backtraces that https://github.com/aristocratos/btop/blob/main/src/linux/btop_collect.cpp#L1108 is the problematic line of code (in the other one the error seems more complex)

**To Reproduce**

1. Have `btop` running (duh)
2. Start the `fstrim.service`  systemd unit (or the equivalent `fstrim` command)
3. If `btop` doesn't crash, repeat step 2

**Expected behavior**

btop should keep running :frog: 

**Screenshots**

![btop crashing with a free() error](https://user-images.githubusercontent.com/19169000/211294849-93bd968c-9d27-40f0-96f8-271b934d0224.png)

![btop crashing with different variation of the same error (or a different error)](https://user-images.githubusercontent.com/19169000/211294890-abcd0b39-b193-4587-837e-39d2b863e728.png)

**Info (please complete the following information):**
 - btop++ version: 1.2.13 (the tagged release)
 - Binary: I tried the Arch Linux binaries and a self-compiled build
 - (If compiled) Compiler and version: GCC 12.2.0
 - Architecture: x86_64
 - Platform: Linux (Arch Linux distro)
 - (Linux) Kernel: 6.1.4-arch1-1
 - Terminal used: Konsole (also happens with gnome-terminal/kgx too)
 - Font used: Noto Sans Mono

**Additional context**

I unfortunately lost the log due to me restarting btop but I don't think it's **that** important

**GDB Backtrace**

<details>
  <summary>Exhibit 1</summary>

  ```
Thread 7 (Thread 0x7f00e1bfe6c0 (LWP 2035)):
#0  0x00007f00e2f1004c in read () from /usr/lib/libc.so.6
#1  0x00007f00e30ca682 in read (__nbytes=8191, __buf=0x558a2a1efc70, __fd=<optimized out>) at /usr/include/bits/unistd.h:38
#2  std::__basic_file<char>::xsgetn (this=this@entry=0x7f00e3233b08 <__gnu_internal::buf_cin+104>, __s=0x558a2a1efc70 "", __n=__n@entry=8191) at basic_file.cc:337
#3  0x00007f00e3111139 in std::basic_filebuf<char, std::char_traits<char> >::underflow (this=0x7f00e3233aa0 <__gnu_internal::buf_cin>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:487
#4  0x00007f00e3149986 in std::basic_streambuf<char, std::char_traits<char> >::uflow (this=0x7f00e3233aa0 <__gnu_internal::buf_cin>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:708
#5  0x00007f00e311eb8e in std::basic_streambuf<char, std::char_traits<char> >::sbumpc (this=<optimized out>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:321
#6  std::basic_streambuf<char, std::char_traits<char> >::sbumpc (this=<optimized out>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:321
#7  std::istream::get (this=0x7f00e32345a0 <std::cin>, __c=@0x7f00e1bfde7f: 0 '\000') at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/istream.tcc:291
#8  0x0000558a28288230 in Input::InputThr::runImpl (this=0x558a2a1c58a0) at src/btop_input.cpp:99
#9  Input::InputThr::run (that=0x558a2a1c58a0) at src/btop_input.cpp:92
#10 0x00007f00e30d62f3 in std::execute_native_thread_routine (__p=0x558a2a2272a0) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#11 0x00007f00e2e9f8fd in ?? () from /usr/lib/libc.so.6
#12 0x00007f00e2f21a60 in ?? () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7f00e3243440 (LWP 2008)):
#0  0x00007f00e2ee67c5 in clock_nanosleep () from /usr/lib/libc.so.6
#1  0x00007f00e2eeb2d7 in nanosleep () from /usr/lib/libc.so.6
#2  0x0000558a282ff2a8 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/include/c++/12.2.0/bits/this_thread_sleep.h:80
#3  Tools::sleep_ms (ms=<optimized out>, ms=<optimized out>) at src/btop_tools.hpp:264
#4  Tools::atomic_wait_for(std::atomic<bool> const&, bool, unsigned long) [clone .constprop.0] (old=old@entry=true, wait_ms=wait_ms@entry=5000, atom=...) at src/btop_tools.cpp:487
#5  0x0000558a2824f07c in Runner::run (box="clock", no_update=<optimized out>, force_redraw=<optimized out>) at src/btop.cpp:617
#6  0x0000558a2822b561 in main (argc=<optimized out>, argv=<optimized out>) at src/btop.cpp:955

Thread 5 (Thread 0x7f00e0ba76c0 (LWP 14377) (Exiting)):
#0  get_cie (f=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde.h:157
#1  get_fde_encoding (f=0x7f00e2fd8588) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde.c:350
#2  find_fde_tail (dbase=0, bases=0x7f00e0ba57f8, hdr=0x7f00e2fbba90, pc=139641784171974) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde-dip.c:455
#3  _Unwind_Find_FDE (pc=0x7f00e2f0fdc6 <open64+182>, bases=bases@entry=0x7f00e0ba57f8) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde-dip.c:513
#4  0x00007f00e3259344 in uw_frame_state_for (context=0x7f00e0ba5750, fs=0x7f00e0ba5490) at /usr/src/debug/gcc/libgcc/unwind-dw2.c:1263
#5  0x00007f00e325a98d in _Unwind_ForcedUnwind_Phase2 (exc=0x7f00e0ba7d30, context=0x7f00e0ba5750, frames_p=0x7f00e0ba5658) at /usr/src/debug/gcc/libgcc/unwind.inc:162
#6  0x00007f00e325b010 in _Unwind_ForcedUnwind (exc=0x7f00e0ba7d30, stop=0x7f00e2ea7cc0, stop_argument=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind.inc:218
#7  0x00007f00e2ea7e57 in ?? () from /usr/lib/libc.so.6
#8  0x00007f00e2e9bdd3 in ?? () from /usr/lib/libc.so.6
#9  0x00007f00e2f0fdc7 in open64 () from /usr/lib/libc.so.6
#10 0x00007f00e2e97e96 in _IO_file_open () from /usr/lib/libc.so.6
#11 0x00007f00e2e9805b in _IO_file_fopen () from /usr/lib/libc.so.6
#12 0x00007f00e2e8c2df in ?? () from /usr/lib/libc.so.6
#13 0x00007f00e30ca5a6 in std::__basic_file<char>::open (this=this@entry=0x7f00e0ba6328, __name=__name@entry=0x558a2a210920 "/sys/block/sda/sda1/stat", __mode=__mode@entry=std::_S_in) at basic_file.cc:254
#14 0x00007f00e31166e0 in std::basic_filebuf<char, std::char_traits<char> >::open (this=this@entry=0x7f00e0ba62c0, __s=0x558a2a210920 "/sys/block/sda/sda1/stat", __mode=std::_S_in) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:185
#15 0x00007f00e31168a5 in std::basic_ifstream<char, std::char_traits<char> >::open (this=0x7f00e0ba62b0, __s=<optimized out>, __mode=<optimized out>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/fstream:665
#16 0x0000558a282d0f13 in std::basic_ifstream<char, std::char_traits<char> >::open<std::filesystem::__cxx11::path> (__mode=std::_S_in, __s=filesystem::path "/sys/block/sda/sda1/stat" = {...}, this=0x7f00e0ba62b0) at /usr/include/c++/12.2.0/bits/basic_string.h:233
#17 Mem::collect (no_update=<optimized out>) at src/linux/btop_collect.cpp:1138
#18 0x0000558a2824be15 in Runner::_runner () at src/btop.cpp:505
#19 0x00007f00e2e9f8fd in ?? () from /usr/lib/libc.so.6
#20 0x00007f00e2f21a60 in ?? () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7f00e13a86c0 (LWP 14373) (Exiting)):
#0  get_cie (f=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde.h:157
#1  get_fde_encoding (f=0x7f00e2fd8588) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde.c:350
#2  find_fde_tail (dbase=0, bases=0x7f00e13a67f8, hdr=0x7f00e2fbba90, pc=139641784171974) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde-dip.c:455
--Type <RET> for more, q to quit, c to continue without paging--c
#3  _Unwind_Find_FDE (pc=0x7f00e2f0fdc6 <open64+182>, bases=bases@entry=0x7f00e13a67f8) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde-dip.c:513
#4  0x00007f00e3259344 in uw_frame_state_for (context=0x7f00e13a6750, fs=0x7f00e13a6490) at /usr/src/debug/gcc/libgcc/unwind-dw2.c:1263
#5  0x00007f00e325a98d in _Unwind_ForcedUnwind_Phase2 (exc=0x7f00e13a8d30, context=0x7f00e13a6750, frames_p=0x7f00e13a6658) at /usr/src/debug/gcc/libgcc/unwind.inc:162
#6  0x00007f00e325b010 in _Unwind_ForcedUnwind (exc=0x7f00e13a8d30, stop=0x7f00e2ea7cc0, stop_argument=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind.inc:218
#7  0x00007f00e2ea7e57 in ?? () from /usr/lib/libc.so.6
#8  0x00007f00e2e9bdd3 in ?? () from /usr/lib/libc.so.6
#9  0x00007f00e2f0fdc7 in open64 () from /usr/lib/libc.so.6
#10 0x00007f00e2e97e96 in _IO_file_open () from /usr/lib/libc.so.6
#11 0x00007f00e2e9805b in _IO_file_fopen () from /usr/lib/libc.so.6
#12 0x00007f00e2e8c2df in ?? () from /usr/lib/libc.so.6
#13 0x00007f00e30ca5a6 in std::__basic_file<char>::open (this=this@entry=0x7f00e13a7328, __name=__name@entry=0x558a2a210920 "/sys/block/sda/sda1/stat", __mode=__mode@entry=std::_S_in) at basic_file.cc:254
#14 0x00007f00e31166e0 in std::basic_filebuf<char, std::char_traits<char> >::open (this=this@entry=0x7f00e13a72c0, __s=0x558a2a210920 "/sys/block/sda/sda1/stat", __mode=std::_S_in) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:185
#15 0x00007f00e31168a5 in std::basic_ifstream<char, std::char_traits<char> >::open (this=0x7f00e13a72b0, __s=<optimized out>, __mode=<optimized out>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/fstream:665
#16 0x0000558a282d0f13 in std::basic_ifstream<char, std::char_traits<char> >::open<std::filesystem::__cxx11::path> (__mode=std::_S_in, __s=filesystem::path "/sys/block/sda/sda1/stat" = {...}, this=0x7f00e13a72b0) at /usr/include/c++/12.2.0/bits/basic_string.h:233
#17 Mem::collect (no_update=<optimized out>) at src/linux/btop_collect.cpp:1138
#18 0x0000558a2824be15 in Runner::_runner () at src/btop.cpp:505
#19 0x00007f00e2e9f8fd in ?? () from /usr/lib/libc.so.6
#20 0x00007f00e2f21a60 in ?? () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7f00d3fff6c0 (LWP 14387)):
#0  0x00007f00e2f199eb in munmap () from /usr/lib/libc.so.6
#1  0x00007f00e2e957e9 in ?? () from /usr/lib/libc.so.6
#2  0x00007f00e2eab3dc in ?? () from /usr/lib/libc.so.6
#3  0x00007f00e2ead737 in ?? () from /usr/lib/libc.so.6
#4  0x00007f00e2eafba3 in free () from /usr/lib/libc.so.6
#5  0x00007f00e30a46da in operator delete (ptr=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/del_op.cc:49
#6  0x00007f00e30a46ea in operator delete (ptr=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/del_ops.cc:33
#7  0x0000558a282cfb33 in std::__new_allocator<char>::deallocate (this=0x7f00d4001070, __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/12.2.0/bits/new_allocator.h:158
#8  std::allocator<char>::deallocate (__n=<optimized out>, __p=<optimized out>, this=0x7f00d4001070) at /usr/include/c++/12.2.0/bits/allocator.h:200
#9  std::allocator_traits<std::allocator<char> >::deallocate (__n=<optimized out>, __p=<optimized out>, __a=...) at /usr/include/c++/12.2.0/bits/alloc_traits.h:496
#10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (__size=<optimized out>, this=0x7f00d4001070) at /usr/include/c++/12.2.0/bits/basic_string.h:292
#11 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x7f00d4001070) at /usr/include/c++/12.2.0/bits/basic_string.h:286
#12 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=<optimized out>, this=<optimized out>) at /usr/include/c++/12.2.0/bits/basic_string.h:795
#13 std::destroy_at<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__location=<optimized out>, __location=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_construct.h:88
#14 std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__pointer=<optimized out>, __pointer=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_construct.h:149
#15 std::_Destroy_aux<false>::__destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*> (__last=<optimized out>, __first=<optimized out>, __first=<optimized out>, __last=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_construct.h:163
#16 std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*> (__last=<optimized out>, __first=<optimized out>, __first=<optimized out>, __last=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_construct.h:196
#17 std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__last=<optimized out>, __first=<optimized out>, __first=<optimized out>, __last=<optimized out>) at /usr/include/c++/12.2.0/bits/alloc_traits.h:850
#18 std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_erase_at_end (__pos=0x7f00d4000ff0, this=0x558a28347608 <Mem::current_mem+168>) at /usr/include/c++/12.2.0/bits/stl_vector.h:1932
#19 std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::clear (this=<optimized out>, this=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_vector.h:1601
#20 Mem::collect (no_update=<optimized out>) at src/linux/btop_collect.cpp:1107
#21 0x0000558a2824be15 in Runner::_runner () at src/btop.cpp:505
#22 0x00007f00e2e9f8fd in ?? () from /usr/lib/libc.so.6
#23 0x00007f00e2f21a60 in ?? () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7f00e23ff6c0 (LWP 2031) (Exiting)):
#0  get_cie (f=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde.h:157
#1  get_fde_encoding (f=0x7f00e2fd8588) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde.c:350
#2  find_fde_tail (dbase=0, bases=0x7f00e23fd7f8, hdr=0x7f00e2fbba90, pc=139641784171974) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde-dip.c:455
#3  _Unwind_Find_FDE (pc=0x7f00e2f0fdc6 <open64+182>, bases=bases@entry=0x7f00e23fd7f8) at /usr/src/debug/gcc/libgcc/unwind-dw2-fde-dip.c:513
#4  0x00007f00e3259344 in uw_frame_state_for (context=0x7f00e23fd750, fs=0x7f00e23fd490) at /usr/src/debug/gcc/libgcc/unwind-dw2.c:1263
#5  0x00007f00e325a98d in _Unwind_ForcedUnwind_Phase2 (exc=0x7f00e23ffd30, context=0x7f00e23fd750, frames_p=0x7f00e23fd658) at /usr/src/debug/gcc/libgcc/unwind.inc:162
#6  0x00007f00e325b010 in _Unwind_ForcedUnwind (exc=0x7f00e23ffd30, stop=0x7f00e2ea7cc0, stop_argument=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind.inc:218
#7  0x00007f00e2ea7e57 in ?? () from /usr/lib/libc.so.6
#8  0x00007f00e2e9bdd3 in ?? () from /usr/lib/libc.so.6
#9  0x00007f00e2f0fdc7 in open64 () from /usr/lib/libc.so.6
#10 0x00007f00e2e97e96 in _IO_file_open () from /usr/lib/libc.so.6
#11 0x00007f00e2e9805b in _IO_file_fopen () from /usr/lib/libc.so.6
#12 0x00007f00e2e8c2df in ?? () from /usr/lib/libc.so.6
#13 0x00007f00e30ca5a6 in std::__basic_file<char>::open (this=this@entry=0x7f00e23fe328, __name=__name@entry=0x558a2a210920 "/sys/block/sda/sda1/stat", __mode=__mode@entry=std::_S_in) at basic_file.cc:254
#14 0x00007f00e31166e0 in std::basic_filebuf<char, std::char_traits<char> >::open (this=this@entry=0x7f00e23fe2c0, __s=0x558a2a210920 "/sys/block/sda/sda1/stat", __mode=std::_S_in) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:185
#15 0x00007f00e31168a5 in std::basic_ifstream<char, std::char_traits<char> >::open (this=0x7f00e23fe2b0, __s=<optimized out>, __mode=<optimized out>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/fstream:665
#16 0x0000558a282d0f13 in std::basic_ifstream<char, std::char_traits<char> >::open<std::filesystem::__cxx11::path> (__mode=std::_S_in, __s=filesystem::path "/sys/block/sda/sda1/stat" = {...}, this=0x7f00e23fe2b0) at /usr/include/c++/12.2.0/bits/basic_string.h:233
#17 Mem::collect (no_update=<optimized out>) at src/linux/btop_collect.cpp:1138
#18 0x0000558a2824be15 in Runner::_runner () at src/btop.cpp:505
#19 0x00007f00e2e9f8fd in ?? () from /usr/lib/libc.so.6
#20 0x00007f00e2f21a60 in ?? () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f00d37fe6c0 (LWP 14390)):
#0  0x00007f00e2ea164c in ?? () from /usr/lib/libc.so.6
#1  0x00007f00e2e51958 in raise () from /usr/lib/libc.so.6
#2  0x00007f00e2e3b53d in abort () from /usr/lib/libc.so.6
#3  0x00007f00e2e957ee in ?? () from /usr/lib/libc.so.6
#4  0x00007f00e2eab3dc in ?? () from /usr/lib/libc.so.6
#5  0x00007f00e2ead737 in ?? () from /usr/lib/libc.so.6
#6  0x00007f00e2eafba3 in free () from /usr/lib/libc.so.6
#7  0x00007f00e30a46da in operator delete (ptr=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/del_op.cc:49
#8  0x00007f00e30a46ea in operator delete (ptr=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/del_ops.cc:33
#9  0x0000558a282cfb33 in std::__new_allocator<char>::deallocate (this=0x7f00d4001070, __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/12.2.0/bits/new_allocator.h:158
#10 std::allocator<char>::deallocate (__n=<optimized out>, __p=<optimized out>, this=0x7f00d4001070) at /usr/include/c++/12.2.0/bits/allocator.h:200
#11 std::allocator_traits<std::allocator<char> >::deallocate (__n=<optimized out>, __p=<optimized out>, __a=...) at /usr/include/c++/12.2.0/bits/alloc_traits.h:496
#12 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (__size=<optimized out>, this=0x7f00d4001070) at /usr/include/c++/12.2.0/bits/basic_string.h:292
#13 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x7f00d4001070) at /usr/include/c++/12.2.0/bits/basic_string.h:286
#14 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=<optimized out>, this=<optimized out>) at /usr/include/c++/12.2.0/bits/basic_string.h:795
#15 std::destroy_at<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__location=<optimized out>, __location=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_construct.h:88
#16 std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__pointer=<optimized out>, __pointer=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_construct.h:149
#17 std::_Destroy_aux<false>::__destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*> (__last=<optimized out>, __first=<optimized out>, __first=<optimized out>, __last=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_construct.h:163
#18 std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*> (__last=<optimized out>, __first=<optimized out>, __first=<optimized out>, __last=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_construct.h:196
#19 std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__last=<optimized out>, __first=<optimized out>, __first=<optimized out>, __last=<optimized out>) at /usr/include/c++/12.2.0/bits/alloc_traits.h:850
#20 std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_erase_at_end (__pos=0x7f00d4000ff0, this=0x558a28347608 <Mem::current_mem+168>) at /usr/include/c++/12.2.0/bits/stl_vector.h:1932
#21 std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::clear (this=<optimized out>, this=<optimized out>) at /usr/include/c++/12.2.0/bits/stl_vector.h:1601
#22 Mem::collect (no_update=<optimized out>) at src/linux/btop_collect.cpp:1107
#23 0x0000558a2824be15 in Runner::_runner () at src/btop.cpp:505
#24 0x00007f00e2e9f8fd in ?? () from /usr/lib/libc.so.6
#25 0x00007f00e2f21a60 in ?? () from /usr/lib/libc.so.6
  ```
</details>

<details>
  <summary>Exhibit 2</summary>

  ```
Thread 4 (Thread 0x7efef27fc6c0 (LWP 19528)):
#0  0x00007eff0bd1017b in access () from /usr/lib/libc.so.6
#1  0x00005570c188ced0 in Mem::collect (no_update=<optimized out>) at /usr/include/c++/12.2.0/bits/basic_string.h:233
#2  0x00005570c1807e15 in Runner::_runner () at src/btop.cpp:505
#3  0x00007eff0bc9f8fd in ?? () from /usr/lib/libc.so.6
#4  0x00007eff0bd21a60 in ?? () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7eff0a9fe6c0 (LWP 16606)):
#0  0x00007eff0bd1004c in read () from /usr/lib/libc.so.6
#1  0x00007eff0beca682 in read (__nbytes=8191, __buf=0x5570c200fc70, __fd=<optimized out>) at /usr/include/bits/unistd.h:38
#2  std::__basic_file<char>::xsgetn (this=this@entry=0x7eff0c033b08 <__gnu_internal::buf_cin+104>, __s=0x5570c200fc70 "", __n=__n@entry=8191) at basic_file.cc:337
#3  0x00007eff0bf11139 in std::basic_filebuf<char, std::char_traits<char> >::underflow (this=0x7eff0c033aa0 <__gnu_internal::buf_cin>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:487
#4  0x00007eff0bf49986 in std::basic_streambuf<char, std::char_traits<char> >::uflow (this=0x7eff0c033aa0 <__gnu_internal::buf_cin>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:708
#5  0x00007eff0bf1eb8e in std::basic_streambuf<char, std::char_traits<char> >::sbumpc (this=<optimized out>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:321
#6  std::basic_streambuf<char, std::char_traits<char> >::sbumpc (this=<optimized out>) at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:321
#7  std::istream::get (this=0x7eff0c0345a0 <std::cin>, __c=@0x7eff0a9fde7f: 0 '\000') at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/istream.tcc:291
#8  0x00005570c1844230 in Input::InputThr::runImpl (this=0x5570c1fe58a0) at src/btop_input.cpp:99
#9  Input::InputThr::run (that=0x5570c1fe58a0) at src/btop_input.cpp:92
#10 0x00007eff0bed62f3 in std::execute_native_thread_routine (__p=0x5570c2049850) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#11 0x00007eff0bc9f8fd in ?? () from /usr/lib/libc.so.6
#12 0x00007eff0bd21a60 in ?? () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7eff0c074440 (LWP 16604)):
#0  0x00007eff0bce67c5 in clock_nanosleep () from /usr/lib/libc.so.6
#1  0x00007eff0bceb2d7 in nanosleep () from /usr/lib/libc.so.6
#2  0x00005570c18bb2a8 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/include/c++/12.2.0/bits/this_thread_sleep.h:80
#3  Tools::sleep_ms (ms=<optimized out>, ms=<optimized out>) at src/btop_tools.hpp:264
#4  Tools::atomic_wait_for(std::atomic<bool> const&, bool, unsigned long) [clone .constprop.0] (old=old@entry=true, wait_ms=wait_ms@entry=5000, atom=...) at src/btop_tools.cpp:487
#5  0x00005570c180b07c in Runner::run (box="clock", no_update=<optimized out>, force_redraw=<optimized out>) at src/btop.cpp:617
#6  0x00005570c17e7561 in main (argc=<optimized out>, argv=<optimized out>) at src/btop.cpp:955

Thread 1 (Thread 0x7eff089a56c0 (LWP 18797) (Exiting)):
#0  0x00007eff0bca164c in ?? () from /usr/lib/libc.so.6
#1  0x00007eff0bc51958 in raise () from /usr/lib/libc.so.6
#2  0x00007eff0bc3b53d in abort () from /usr/lib/libc.so.6
#3  0x00007eff0bc957ee in ?? () from /usr/lib/libc.so.6
#4  0x00007eff0bcab3dc in ?? () from /usr/lib/libc.so.6
#5  0x00007eff0bcac064 in ?? () from /usr/lib/libc.so.6
#6  0x00007eff0bcad540 in ?? () from /usr/lib/libc.so.6
#7  0x00007eff0bcafba3 in free () from /usr/lib/libc.so.6
#8  0x00007eff0bcafc92 in ?? () from /usr/lib/libc.so.6
#9  0x00007eff0bc9f783 in ?? () from /usr/lib/libc.so.6
#10 0x00007eff0bd21a60 in ?? () from /usr/lib/libc.so.6
  ```
</details>

**Comment by TheComputerGuy96** [comment]
I haven't encountered crashes in btop in a while (except for when a GPU driver crashed really hard) so I think something must have solved this
