### ISSUE TITLE
[BUG] Crash on wayland | Bus Error

### ISSUE THREAD

**Issue by aaruni96** [aristocratos/btop#736]
**Describe the bug**

When running on wayland / hyprland , btop dies with message "bus error (core dumped)".

I am new to wayland/hyprland, so it is possible I have done something wrong in this environment, but any explanation will be appreciated.

**To Reproduce**

In Hyprland, try to start btop

**Expected behavior**

btop starts

**Info (please complete the following information):**
 - btop++ version: `btop version: 1.3.0`
 - Binary: binary from arch repo `extra/btop 1.3.0-2`
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 6.7.0-zen3-1-zen
 - Terminal used: `mate-terminal` / `zsh`

**Additional context**

Contents of `~/.config/btop/btop.log`

Note: The snap uses: `~/snap/btop/current/.config/btop`

(try running btop with `--debug` flag if btop.log is empty)

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

crash in GDB :
```
Program received signal SIGBUS, Bus error.
0x000055555556618e9 in Gpu::Rsmi::collect<true> (gpus_slic=0x55555574f5a0) at src/linux/btrop_collect.cpp:1384
1384                      } else gpus_slice[i].mem_cloc_speed =(long long_frequencies.frequency[frequencies.current]/1000000; //Hz to Mhz
```

Backtrace :
```
#0 0x00005555556618e9 in Gpu:Rsmi:collect<true> (gpus_slice=0x55555574f5a0) at src/linux/btop_collect.cpp:1384
#1 Gpu::Rsmi::init() [clone .isra.0] () at src/linux/btop_collect.cpp:1298
#2 0x000055555562dd55 in Shared::init() at src/linux/btop_collect.cpp:268
#3 0x0000555555577f5c in main (argc=<optimized out>, argv=<optimized out>) at src/btop.cpp:1015
```

**Comment by aaruni96** [comment]
Uh, nevermind I think? It works again after a reboot.
