### ISSUE TITLE
[BUG] WSL1: use of key-bindings results in frozen state

### ISSUE THREAD

**Issue by Gregory-K** [aristocratos/btop#815]
**Describe the bug**

`btop` starts OK, but none of the key-bindings work. The program stops updating the display right after pressing any key and gets frozen. No escape/quit sequence works except for killing the terminal(or tmux) window.

**To Reproduce**

- Download latest `btop-x86_64-linux-musl.tbz`
- Extract
- Run
  - ./bin/btop OR
  - make install && make setuid > btop

**Expected behaviour**

At least a working 'q' to exit.

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: `btop++ v.1.3.2`
 - Binary: static binary from release
 - Architecture: `x86_64`
 - Platform: `Windows Subsystem for Linux`
 - (Linux) Kernel: `4.4.0-19041-Microsoft` (WSL Debian 11)
 - Terminal used: `mintty/wsltty` / default wsl provided / inside `pwsh`
 - Font used: `Cascadia Mono`

**Additional context**

Contents of `~/.config/btop/btop.log`

```log
# normal execution, after killing term window
===> btop++ v.1.3.2
ERROR: Couldn't determine terminal size of "STDOUT_FILENO"!
ERROR: Couldn't determine terminal size of "/dev/tty"!

# debug flag
===> btop++ v.1.3.2
DEBUG: Running in DEBUG mode!
INFO: Logger set to DEBUG
DEBUG: Using locale en_GB.UTF-8
INFO: Running on /dev/pts/5
DEBUG: Shared::init() : Initialized.
```

**GDB Backtrace**

I didn't follow the backtrace procedure.  
The issue is not of much importance for me, but I'm willing if asked to.

**Comment by Bu11etmagnet** [comment]
After running btop under gdb, pressing `m` freezes the display as described. Pressing Ctrl-C breaks into the debugger, then:

```
(gdb) thread apply all bt

Thread 2 (Thread 0x7fffff1606c0 (LWP 24028) "btop"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000000008036f5e in std::__detail::__platform_wait<int> (__addr=0x82a99c4 <Runner::do_work>, __val=0) at /usr/include/c++/14/bits/atomic_wait.h:112
#2  0x00000000080380ca in std::__atomic_wait_address_bare<std::__atomic_semaphore::_M_acquire()::{lambda()#1}>(int const*, std::__atomic_semaphore::_M_acquire()::{lambda()#1}) (__addr=0x82a99c4 <Runner::do_work>, __pred=...) at /usr/include/c++/14/bits/atomic_wait.h:448
#3  0x00000000080381c3 in std::__atomic_semaphore::_M_acquire (this=0x82a99c4 <Runner::do_work>) at /usr/include/c++/14/bits/semaphore_base.h:215
#4  std::counting_semaphore<1l>::acquire (this=0x82a99c4 <Runner::do_work>) at /usr/include/c++/14/semaphore:75
#5  0x0000000008034f42 in Runner::thread_wait () at src/btop.cpp:375
#6  0x0000000008021859 in Runner::_runner () at src/btop.cpp:476
#7  0x00007fffff26caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#8  0x00007fffff2f9a34 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100

Thread 1 (Thread 0x7fffff1c0740 (LWP 24024) "btop"):
#0  0x00007fffff2eba9a in __GI___libc_read (nbytes=1024, buf=0x7ffffffed600, fd=0) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=0, buf=0x7ffffffed600, nbytes=1024) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x000000000811d986 in Input::poll (timeout=1000) at src/btop_input.cpp:113
#3  0x0000000008027937 in btop_main (args=Python Exception <class 'gdb.error'>: No symbol "static_cast" in current context.
...) at src/btop.cpp:1188
#4  0x000000000818f1cb in main (argc=1, argv=0x7ffffffee0d8) at src/main.cpp:11
Warning: the current language does not match this frame.
```
