### ISSUE TITLE
btop freezes after a while (no interaction, no apparent cause)

### ISSUE THREAD

**Issue by tomterl** [aristocratos/btop#83]
**Describe the bug**

I have btop running in a tmux window; after a while it will freeze, i.e. no visual changes, no reaction to user input.

**To Reproduce**

Just let btop run unattended for a while

**Expected behavior**

Continued operation :)

**Info (please complete the following information):**
 - btop++ version: 1.0.15
 - Binary: self-compiled (static), as well as provided release
 - (If compiled) Compiler and version: g++-10 10.3.0 
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.4.0-88-generic
- Terminal used: konsole 19.12.3
 - Font used: Jet Brains Mono

**GDB Backtrace**
First thread:

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__pthread_clockjoin_ex (threadid=140076569601792, thread_return=thread_return@entry=0x0, clockid=clockid@entry=0,
    abstime=abstime@entry=0x0, block=block@entry=true) at pthread_join_common.c:145
145     pthread_join_common.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __pthread_clockjoin_ex (threadid=140076569601792, thread_return=thread_return@entry=0x0, clockid=clockid@entry=0,
    abstime=abstime@entry=0x0, block=block@entry=true) at pthread_join_common.c:145
#1  0x00000000005b1dc3 in __pthread_join (threadid=<optimized out>, thread_return=thread_return@entry=0x0) at pthread_join.c:24
#2  0x000000000045b209 in clean_quit (sig=<optimized out>) at src/btop.cpp:203
#3  0x00000000005d3fcd in __run_exit_handlers ()
#4  0x00000000005d41b0 in exit ()
#5  0x0000000000470240 in Runner::stop () at src/btop.cpp:645
#6  0x000000000045e15a in term_resize (force=<optimized out>) at src/btop.cpp:162
#7  <signal handler called>
#8  __lll_lock_wait (futex=futex@entry=0x72a940 <Runner::active_mtx>, private=0) at lowlevellock.c:52
#9  0x00000000005b28e3 in __pthread_mutex_lock (mutex=0x72a940 <Runner::active_mtx>) at ../nptl/pthread_mutex_lock.c:80
#10 0x000000000047277c in Runner::thread_lock::thread_lock (mtx=..., this=<synthetischer Zeiger>) at src/btop.cpp:296
#11 Runner::run (box=..., no_update=<optimized out>, force_redraw=<optimized out>) at src/btop.cpp:597
#12 0x000000000041a6df in main (argc=<optimized out>, argv=<optimized out>) at src/btop.cpp:880
```

Second thread:
```
#0  __pthread_clockjoin_ex (threadid=140076552816384, thread_return=0x0, clockid=<optimized out>, abstime=<optimized out>,
    block=<optimized out>) at pthread_join_common.c:145
#1  0x000000000056dfa7 in std::thread::join() ()
#2  0x000000000046ff51 in std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::~_Async_state_impl (
    this=<optimized out>, this=<optimized out>) at /usr/include/c++/10/future:1697
#3  std::destroy_at<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&> > (__location=0x7f66180207f0)
    at /usr/include/c++/10/bits/stl_construct.h:88
#4  std::allocator_traits<std::allocator<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&> > >::destroy<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&> > (__p=0x7f66180207f0, __a=...)
    at /usr/include/c++/10/bits/alloc_traits.h:533
#5  std::_Sp_counted_ptr_inplace<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>, std::allocator<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x7f66180207e0)
    at /usr/include/c++/10/bits/shared_ptr_base.h:560
#6  0x000000000044633a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f66180207e0)
    at /usr/include/c++/10/bits/shared_ptr_base.h:158
#7  0x000000000046421b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/10/bits/shared_ptr_base.h:733
#8  std::__shared_ptr<std::__future_base::_State_baseV2, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    this=<optimized out>) at /usr/include/c++/10/bits/shared_ptr_base.h:1183
#9  std::shared_ptr<std::__future_base::_State_baseV2>::~shared_ptr (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/10/bits/shared_ptr.h:121
#10 std::__basic_future<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::~__basic_future (this=<optimized out>,
    this=<optimized out>) at /usr/include/c++/10/future:682
#11 std::future<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::~future (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/10/future:815
#12 Runner::_runner (_=<optimized out>) at src/btop.cpp:417
#13 0x00000000005b0a19 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x000000000063f133 in clone ()
```

Third thread:
```
#0  0x000000000053fa06 in std::istream::sentry::sentry(std::istream&, bool) () at pthread_create.c:679
#1  0x00000000004eff39 in std::istream::ignore(long, int) () at pthread_create.c:679
#2  0x00000000004a9e92 in Proc::collect (no_update=<optimized out>) at src/linux/btop_collect.cpp:1432
#3  0x000000000046f382 in std::__invoke_impl<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> (__f=<optimized out>) at /usr/include/c++/10/bits/invoke.h:60
#4  std::__invoke<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> (__fn=<optimized out>)
    at /usr/include/c++/10/bits/invoke.h:95
#5  std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >::_M_invoke<0ul, 1ul>
    (this=<optimized out>) at /usr/include/c++/10/thread:264
#6  std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >::operator() (
    this=<optimized out>) at /usr/include/c++/10/thread:271
#7  std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::operator() (this=0x7f661d2c0230)
    at /usr/include/c++/10/future:1350
#8  std::__invoke_impl<std::unique_ptr<std::__future_base::_Result<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>&> (__f=...)
    at /usr/include/c++/10/bits/invoke.h:60
#9  std::__invoke_r<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>&> (__fn=...) at /usr/include/c++/10/bits/invoke.h:115
#10 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/10/bits/std_function.h:292
#11 0x000000000045a37f in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (this=<optimized out>) at /usr/include/c++/10/bits/std_function.h:622
#12 std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (this=0x7f66180207f0, __f=<optimized out>, __did_set=0x7f661d2c0207) at /usr/include/c++/10/future:572
#13 0x00000000005b3b3f in __pthread_once_slow (once_control=0x7f6618020808, init_routine=0x55a640 <__once_proxy>) at pthread_once.c:116
#14 0x0000000000470718 in __gthread_once (__func=<optimized out>, __once=0x7f6618020808)
    at /usr/include/x86_64-linux-gnu/c++/10/bits/gthr-default.h:700
#15 std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__f=
    @0x7f661d2c0220: (void (std::__future_base::_State_baseV2::*)(class std::__future_base::_State_baseV2 * const, class std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x45a360 <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>,
    __once=...) at /usr/include/c++/10/mutex:729
#16 std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) (__ignore_failure=false, __res=..., this=0x7f66180207f0) at /usr/include/c++/10/future:412
#17 std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::_Async_state_impl(std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >&&)::{lambda()#1}::operator()() const (this=<optimized out>)
    at /usr/include/c++/10/future:1682
#18 std::__invoke_impl<void, std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::_Async_state_impl(std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >&&)::{lambda()#1}>(std::__invoke_other, std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::_Async_state_impl(std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >&&)::{lambda()#1}&&) (__f=...)
    at /usr/include/c++/10/bits/invoke.h:60
#19 std::__invoke<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::_Async_state_impl(std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >&&)::{lambda()#1}>(std::__invoke_result&&, (std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::_Async_state_impl(std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >&&)::{lambda()#1}&&)...) (__fn=...) at /usr/include/c++/10/bits/invoke.h:95
#20 std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::_Async_state_impl(std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >&&)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x7f6618038f08) at /usr/include/c++/10/thread:264
#21 std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::_Async_state_impl(std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >&&)::{lambda()#1}> >::operator()() (this=0x7f6618038f08) at /usr/include/c++/10/thread:271
#22 std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >, std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >&>::_Async_state_impl(std::thread::_Invoker<std::tuple<std::vector<Proc::proc_info, std::allocator<Proc::proc_info> >& (*)(bool), bool> >&&)::{lambda()#1}> > >::_M_run() (this=0x7f6618038f00) at /usr/include/c++/10/thread:215
#23 0x000000000056dd44 in execute_native_thread_routine () at pthread_create.c:679
#24 0x00000000005b0a19 in start_thread (arg=<optimized out>) at pthread_create.c:477
#25 0x000000000063f133 in clone ()
```

**Comment by tomterl** [comment]
It's now running since friday morning without hick-up; no debug-log entries; memory consumption went down from ~5MiB to ~3.5MiB (as reported by btop itself :) )
Very Cool!
